[package]
name = "amd_order"
version = "0.1.0"
authors = ["Richard Lincoln <r.w.lincoln@gmail.com>"]
edition = "2018"

[dependencies]
num-traits = "0.2"

[features]
debug1 = []
debug2 = ["debug1"]
debug3 = ["debug2"]
debug4 = ["debug3"]